services:
  - type: worker
    name: caytonbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
